name: Node.js CI

on:
  push:
  pull_request:
    branches: [master]

env:
  CI: true
  FORCE_COLOR: 2

jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ['10.x', '12.x', '14].x']
        os: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install
      - run: yarn install
      - name: Lint
      - run: yarn run lint
